name: Test Code
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: echo "@davidglaeseman:registry=https://npm.pkg.github.com" >> .npmrc
      - run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      - run: yarn
      - run: yarn build
      - run: yarn test
        shell: bash
